# Generated by Django 4.2.3 on 2023-10-27 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libro', '0004_libro_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='portado',
            new_name='portada',
        ),
    ]
