# Generated by Django 4.2.3 on 2023-10-22 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lector', '0002_alter_prestamo_libro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lector',
            name='nacionalidad',
            field=models.CharField(max_length=30),
        ),
    ]
