# Generated by Django 4.2.3 on 2023-10-22 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lector', '0003_alter_lector_nacionalidad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lector',
            options={'verbose_name': 'Lector', 'verbose_name_plural': 'Lectores'},
        ),
    ]
